jobs:
- job: Win32
  pool:
    vmImage: 'vs2015-win2012r2'
  steps:
  - script: |
      git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg
      git checkout 29be95a5e58d00ecd6ec85ff66171d0d3d19ccd0
      call .\bootstrap-vcpkg.bat
      call .\vcpkg install qt5-base boost catch2 eigen3 nlohmann-json --triplet x86-windows-static
      call .\vcpkg export qt5-base boost catch2 eigen3 nlohmann-json --output="vcpkg-export-x86-windows-static"
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'vcpkg/vcpkg-export-x86-windows-static.zip'
      artifactName: 'Win32_Artifacts'
