jobs:
- job: Win32
  timeoutInMinutes: 0
  pool:
    vmImage: 'vs2015-win2012r2'
  steps:
  - script: |
      git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg
      git checkout 0e759709ddc7dbad0b881f9f068f1b04b2092773
      call .\bootstrap-vcpkg.bat
      call .\vcpkg install boost --triplet x86-windows-static
      call .\vcpkg export boost --triplet x86-windows-static --zip --output="vcpkg-export-x86-windows-static"
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'vcpkg/vcpkg-export-x86-windows-static.zip'
      artifactName: 'Win32_Artifacts'

- job: Win64
  timeoutInMinutes: 0
  pool:
    vmImage: 'vs2015-win2012r2'
  steps:
  - script: |
      git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg
      git checkout 0e759709ddc7dbad0b881f9f068f1b04b2092773
      call .\bootstrap-vcpkg.bat
      call .\vcpkg install boost --triplet x64-windows-static
      call .\vcpkg export boost --triplet x86-windows-static --zip --output="vcpkg-export-x64-windows-static"
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'vcpkg/vcpkg-export-x64-windows-static.zip'
      artifactName: 'Win64_Artifacts'

- job: MacOS
  timeoutInMinutes: 0
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: |
      brew install --with-toolchain llvm
      git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg
      git checkout fb36b4e17c134796bf8e31bf908c2a0c6b2fefc4
      ./bootstrap-vcpkg.sh
      ./vcpkg install boost catch2 eigen3 nlohmann-json --triplet x64-osx
      ./vcpkg export boost catch2 eigen3 nlohmann-json --triplet x64-osx --zip --output="vcpkg-export-x64-osx"
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'vcpkg/vcpkg-export-x64-osx.zip'
      artifactName: 'MacOS_Artifacts'

- job: Linux
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg
      git checkout fb36b4e17c134796bf8e31bf908c2a0c6b2fefc4
      ./bootstrap-vcpkg.sh
      ./vcpkg install boost catch2 eigen3 nlohmann-json --triplet x64-linux
      ./vcpkg export boost catch2 eigen3 nlohmann-json --triplet x64-linux --zip --output="vcpkg-export-x64-linux"
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'vcpkg/vcpkg-export-x64-linux.zip'
      artifactName: 'Linux_Artifacts'
