jobs:
- job: Win32
  timeoutInMinutes: 0
  pool:
    vmImage: 'vs2015-win2012r2'
  steps:
  - script: |
      git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg
      git checkout 29be95a5e58d00ecd6ec85ff66171d0d3d19ccd0
      call .\bootstrap-vcpkg.bat
      call .\vcpkg install qt5-base boost catch2 eigen3 nlohmann-json --triplet x86-windows-static
      call .\vcpkg export qt5-base boost catch2 eigen3 nlohmann-json --zip --output="vcpkg-export-x86-windows-static"
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'vcpkg/vcpkg-export-x86-windows-static.zip'
      artifactName: 'Win32_Artifacts'

- job: Win64
  timeoutInMinutes: 0
  pool:
    vmImage: 'vs2015-win2012r2'
  steps:
  - script: |
      git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg
      git checkout 29be95a5e58d00ecd6ec85ff66171d0d3d19ccd0
      call .\bootstrap-vcpkg.bat
      call .\vcpkg install qt5-base boost catch2 eigen3 nlohmann-json --triplet x64-windows-static
      call .\vcpkg export qt5-base boost catch2 eigen3 nlohmann-json --zip --output="vcpkg-export-x64-windows-static"
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'vcpkg/vcpkg-export-x64-windows-static.zip'
      artifactName: 'Win64_Artifacts'

- job: MacOS
  timeoutInMinutes: 0
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg
      git checkout 29be95a5e58d00ecd6ec85ff66171d0d3d19ccd0
      ./bootstrap-vcpkg.sh
      ./vcpkg install boost catch2 eigen3 nlohmann-json --triplet x64-osx
      ./vcpkg export boost catch2 eigen3 nlohmann-json --zip --output="vcpkg-export-x64-osx"
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'vcpkg/vcpkg-export-x64-osx.zip'
      artifactName: 'MacOS_Artifacts'

- job: Linux
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg
      git checkout 29be95a5e58d00ecd6ec85ff66171d0d3d19ccd0
      ./bootstrap-vcpkg.sh
      ./vcpkg install boost catch2 eigen3 nlohmann-json --triplet x64-linux
      ./vcpkg export boost catch2 eigen3 nlohmann-json --zip --output="vcpkg-export-x64-linux"
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'vcpkg/vcpkg-export-x64-linux.zip'
      artifactName: 'Linux_Artifacts'
