jobs:
- job: Win32
  pool:
    vmImage: 'vs2015-win2012r2'
  steps:
  - script: |
      git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg
      echo "TEST"
      .\bootstrap-vcpkg.bat
      echo "TEST"
      .\vcpkg install boost catch2 eigen3 nlohmann-json qt5-base --triplet x86-windows-static
      echo "TEST"
      .\vcpkg export boost catch2 eigen3 nlohmann-json qt5-base
      echo "TEST"
